use std::cell::RefCell;
use std::ffi::{CStr, CString, c_char};

use crate::{Marina, ResolveResult};

pub const MARINA_RESOLVE_ERROR: i32 = -1;
pub const MARINA_RESOLVE_LOCAL: i32 = 0;
pub const MARINA_RESOLVE_CACHED: i32 = 1;
pub const MARINA_RESOLVE_REMOTE_AVAILABLE: i32 = 2;

#[repr(C)]
pub struct MarinaResolveDetailed {
    pub kind: i32,
    pub path: *mut c_char,
    pub bag: *mut c_char,
    pub registry: *mut c_char,
    pub message: *mut c_char,
}

thread_local! {
    static LAST_ERROR: RefCell<Option<CString>> = const { RefCell::new(None) };
}

fn set_last_error(msg: impl Into<String>) {
    let fallback = CString::new("unknown error").expect("CString literal");
    let cmsg = CString::new(msg.into()).unwrap_or(fallback);
    LAST_ERROR.with(|slot| {
        *slot.borrow_mut() = Some(cmsg);
    });
}

fn clear_last_error() {
    LAST_ERROR.with(|slot| {
        *slot.borrow_mut() = None;
    });
}

fn read_cstr(ptr: *const c_char, arg_name: &str) -> Result<String, String> {
    if ptr.is_null() {
        return Err(format!("{} was null", arg_name));
    }
    // SAFETY: caller guarantees a valid null-terminated C string pointer.
    let s = unsafe { CStr::from_ptr(ptr) };
    s.to_str()
        .map(|v| v.to_string())
        .map_err(|_| format!("{} was not valid UTF-8", arg_name))
}

fn cstring_from_string(s: String) -> *mut c_char {
    match CString::new(s) {
        Ok(v) => v.into_raw(),
        Err(_) => {
            set_last_error("result string contained interior NUL byte");
            std::ptr::null_mut()
        }
    }
}

fn cstring_from_opt(s: Option<String>) -> *mut c_char {
    match s {
        Some(v) => cstring_from_string(v),
        None => std::ptr::null_mut(),
    }
}

fn detailed_error(msg: String) -> MarinaResolveDetailed {
    set_last_error(msg.clone());
    MarinaResolveDetailed {
        kind: MARINA_RESOLVE_ERROR,
        path: std::ptr::null_mut(),
        bag: std::ptr::null_mut(),
        registry: std::ptr::null_mut(),
        message: cstring_from_string(msg),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn marina_resolve_detailed(target: *const c_char) -> MarinaResolveDetailed {
    clear_last_error();

    let target = match read_cstr(target, "target") {
        Ok(v) => v,
        Err(e) => return detailed_error(e),
    };

    let marina = match Marina::load() {
        Ok(v) => v,
        Err(e) => return detailed_error(format!("failed to load marina: {e}")),
    };

    match marina.resolve_target(&target) {
        Ok(ResolveResult::LocalPath(p)) => MarinaResolveDetailed {
            kind: MARINA_RESOLVE_LOCAL,
            path: cstring_from_string(p.display().to_string()),
            bag: std::ptr::null_mut(),
            registry: std::ptr::null_mut(),
            message: cstring_from_string("local path resolved".to_string()),
        },
        Ok(ResolveResult::Cached(p)) => MarinaResolveDetailed {
            kind: MARINA_RESOLVE_CACHED,
            path: cstring_from_string(p.display().to_string()),
            bag: std::ptr::null_mut(),
            registry: std::ptr::null_mut(),
            message: cstring_from_string("cached path resolved".to_string()),
        },
        Ok(ResolveResult::RemoteAvailable { bag, registry, .. }) => MarinaResolveDetailed {
            kind: MARINA_RESOLVE_REMOTE_AVAILABLE,
            path: std::ptr::null_mut(),
            bag: cstring_from_string(bag.to_string()),
            registry: cstring_from_string(registry),
            message: cstring_from_string(
                "remote bag available; call marina_pull(...) to fetch".to_string(),
            ),
        },
        Err(e) => detailed_error(format!("resolve failed: {e}")),
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn marina_free_resolve_detailed(result: *mut MarinaResolveDetailed) {
    if result.is_null() {
        return;
    }
    // SAFETY: caller passes pointer to a struct obtained from marina_resolve_detailed.
    unsafe {
        marina_free_string((*result).path);
        marina_free_string((*result).bag);
        marina_free_string((*result).registry);
        marina_free_string((*result).message);
        (*result).path = std::ptr::null_mut();
        (*result).bag = std::ptr::null_mut();
        (*result).registry = std::ptr::null_mut();
        (*result).message = std::ptr::null_mut();
    }
}

#[unsafe(no_mangle)]
pub extern "C" fn marina_resolve(target: *const c_char) -> *mut c_char {
    let mut detailed = marina_resolve_detailed(target);
    let out = if detailed.kind == MARINA_RESOLVE_LOCAL || detailed.kind == MARINA_RESOLVE_CACHED {
        cstring_from_opt(Some(
            // SAFETY: pointer generated by this library.
            unsafe { CStr::from_ptr(detailed.path) }
                .to_string_lossy()
                .to_string(),
        ))
    } else if detailed.kind == MARINA_RESOLVE_REMOTE_AVAILABLE {
        let bag = if detailed.bag.is_null() {
            "<unknown>".to_string()
        } else {
            // SAFETY: pointer generated by this library.
            unsafe { CStr::from_ptr(detailed.bag) }
                .to_string_lossy()
                .to_string()
        };
        let registry = if detailed.registry.is_null() {
            "<unknown>".to_string()
        } else {
            // SAFETY: pointer generated by this library.
            unsafe { CStr::from_ptr(detailed.registry) }
                .to_string_lossy()
                .to_string()
        };
        cstring_from_string(format!("REMOTE:{}@{}", bag, registry))
    } else {
        std::ptr::null_mut()
    };
    marina_free_resolve_detailed(&mut detailed);
    out
}

#[unsafe(no_mangle)]
pub extern "C" fn marina_pull(bag_ref: *const c_char, registry: *const c_char) -> *mut c_char {
    clear_last_error();

    let bag_ref = match read_cstr(bag_ref, "bag_ref") {
        Ok(v) => v,
        Err(e) => {
            set_last_error(e);
            return std::ptr::null_mut();
        }
    };

    let registry = if registry.is_null() {
        None
    } else {
        match read_cstr(registry, "registry") {
            Ok(v) => Some(v),
            Err(e) => {
                set_last_error(e);
                return std::ptr::null_mut();
            }
        }
    };

    let bag = match bag_ref.parse() {
        Ok(v) => v,
        Err(e) => {
            set_last_error(format!("invalid bag reference: {e}"));
            return std::ptr::null_mut();
        }
    };

    let mut marina = match Marina::load() {
        Ok(v) => v,
        Err(e) => {
            set_last_error(format!("failed to load marina: {e}"));
            return std::ptr::null_mut();
        }
    };

    let path = match marina.pull_exact(&bag, registry.as_deref()) {
        Ok(v) => v,
        Err(e) => {
            set_last_error(format!("pull failed: {e}"));
            return std::ptr::null_mut();
        }
    };

    cstring_from_string(path.display().to_string())
}

#[unsafe(no_mangle)]
pub extern "C" fn marina_last_error_message() -> *mut c_char {
    LAST_ERROR.with(|slot| match &*slot.borrow() {
        Some(err) => match CString::new(err.to_bytes()) {
            Ok(copy) => copy.into_raw(),
            Err(_) => std::ptr::null_mut(),
        },
        None => std::ptr::null_mut(),
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn marina_free_string(ptr: *mut c_char) {
    if ptr.is_null() {
        return;
    }
    // SAFETY: pointer must have been allocated by CString::into_raw in this library.
    unsafe {
        let _ = CString::from_raw(ptr);
    }
}
